apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-webui-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-webui  # The name of Deployment
  minReplicas: 1 
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization (50% is typical, adjust as needed)
