apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services", "replicationcontrollers", "deployments", "configmaps", "secrets", "namespaces"]
    verbs: ["get", "list", "create", "update", "delete"]
