apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: jenkins-cluster-role  # The cluster-wide role you defined earlier
  apiGroup: rbac.authorization.k8s.io
